export default {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/rDa3SfEijeRNCWtHQZCwfbGxYvR.jpg',
      genre_ids: [28, 878, 12, 14, 53],
      id: 539972,
      original_language: 'en',
      original_title: 'Kraven the Hunter',
      overview:
        "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      popularity: 4616.142,
      poster_path: '/i47IUSsN126K11JUzqQIOi1Mg1M.jpg',
      release_date: '2024-12-11',
      title: 'Kraven the Hunter',
      video: false,
      vote_average: 6.5,
      vote_count: 633,
    },
    {
      adult: false,
      backdrop_path: '/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg',
      genre_ids: [12, 10751, 16],
      id: 762509,
      original_language: 'en',
      original_title: 'Mufasa: The Lion King',
      overview:
        'Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.',
      popularity: 3251.854,
      poster_path: '/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg',
      release_date: '2024-12-18',
      title: 'Mufasa: The Lion King',
      video: false,
      vote_average: 7.4,
      vote_count: 782,
    },
    {
      adult: false,
      backdrop_path: '/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg',
      genre_ids: [28, 878, 12],
      id: 912649,
      original_language: 'en',
      original_title: 'Venom: The Last Dance',
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      popularity: 1924.852,
      poster_path: '/aosm8NMQ3UyoBVpSxyimorCQykC.jpg',
      release_date: '2024-10-22',
      title: 'Venom: The Last Dance',
      video: false,
      vote_average: 6.8,
      vote_count: 2458,
    },
    {
      adult: false,
      backdrop_path: '/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg',
      genre_ids: [28, 12, 18],
      id: 558449,
      original_language: 'en',
      original_title: 'Gladiator II',
      overview:
        'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.',
      popularity: 2051.344,
      poster_path: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
      release_date: '2024-11-05',
      title: 'Gladiator II',
      video: false,
      vote_average: 6.8,
      vote_count: 2412,
    },
    {
      adult: false,
      backdrop_path: '/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg',
      genre_ids: [16, 12, 10751, 35],
      id: 1241982,
      original_language: 'en',
      original_title: 'Moana 2',
      overview:
        "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      popularity: 1880.313,
      poster_path: '/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg',
      release_date: '2024-11-21',
      title: 'Moana 2',
      video: false,
      vote_average: 6.997,
      vote_count: 873,
    },
    {
      adult: false,
      backdrop_path: '/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg',
      genre_ids: [16, 14, 28, 12],
      id: 839033,
      original_language: 'en',
      original_title: 'The Lord of the Rings: The War of the Rohirrim',
      overview:
        'A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.',
      popularity: 1177.194,
      poster_path: '/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg',
      release_date: '2024-12-05',
      title: 'The Lord of the Rings: The War of the Rohirrim',
      video: false,
      vote_average: 6.6,
      vote_count: 341,
    },
    {
      adult: false,
      backdrop_path: '/kylozAI9Rf1pp7pZ8nFPK4s1s5n.jpg',
      genre_ids: [28, 12, 14, 16],
      id: 1357633,
      original_language: 'ja',
      original_title: '俺だけレベルアップな件 -ReAwakening-',
      overview:
        "Over a decade after 'gates' connecting worlds appeared, awakening 'hunters' with superpowers, weakest hunter Sung Jinwoo encounters a double dungeon and accepts a mysterious quest, becoming the only one able to level up, changing his fate. A catch-up recap of the first season coupled with an exclusive sneak peek of the first two episodes of the highly anticipated second season in one momentous theatrical fan experience.",
      popularity: 1015.986,
      poster_path: '/uzHMp5heVLR68kbbUEXFPsmxYsM.jpg',
      release_date: '2024-11-26',
      title: 'Solo Leveling -ReAwakening-',
      video: false,
      vote_average: 7,
      vote_count: 77,
    },
    {
      adult: false,
      backdrop_path: '/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg',
      genre_ids: [16, 14, 12],
      id: 823219,
      original_language: 'lv',
      original_title: 'Straume',
      overview:
        'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.',
      popularity: 743.872,
      poster_path: '/imKSymKBK7o73sajciEmndJoVkR.jpg',
      release_date: '2024-08-29',
      title: 'Flow',
      video: false,
      vote_average: 8.413,
      vote_count: 816,
    },
    {
      adult: false,
      backdrop_path: '/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg',
      genre_ids: [16, 12, 35, 10751],
      id: 1022789,
      original_language: 'en',
      original_title: 'Inside Out 2',
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 529.301,
      poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
      release_date: '2024-06-11',
      title: 'Inside Out 2',
      video: false,
      vote_average: 7.569,
      vote_count: 5367,
    },
    {
      adult: false,
      backdrop_path: '/ovt5KdS1oNwXkFPsgymhMoKvxKa.jpg',
      genre_ids: [16, 35, 10751, 12],
      id: 929204,
      original_language: 'en',
      original_title: 'Wallace & Gromit: Vengeance Most Fowl',
      overview:
        'Gromit’s concern that Wallace is becoming too dependent on his inventions proves justified, when Wallace invents a “smart” gnome that seems to develop a mind of its own. When it emerges that a vengeful figure from the past might be masterminding things, it falls to Gromit to battle sinister forces and save his master… or Wallace may never be able to invent again!',
      popularity: 450.63,
      poster_path: '/6BxK38ehxuX2dJmZIMpJcVNbYks.jpg',
      release_date: '2024-12-18',
      title: 'Wallace & Gromit: Vengeance Most Fowl',
      video: false,
      vote_average: 7.7,
      vote_count: 257,
    },
    {
      adult: false,
      backdrop_path: '/w6MAE6cs8F62iAspnIqwVksAENM.jpg',
      genre_ids: [16, 12, 14],
      id: 1208491,
      original_language: 'fr',
      original_title: 'Zak & Wowo, la légende de Lendarys',
      overview:
        "At the heart of an imaginary world populated by fantastical creatures and dangerous monsters, the 13 year-old Zak goes in search of his twin brother Kyle, who has disappeared mysteriously. Equipped with a magical jade stone whose superpowers he doesn't yet know how to control, he is joined by his grandmother NaïNaï and Indiana, a beautiful outlaw who can communicate with the world's fantastical creatures. But he is also flanked by Wowo, formerly a 3 meter-tall furry pachyderm, now turned into a tiny, cute and wacky furball by the magical jade stone.",
      popularity: 493.986,
      poster_path: '/tgOq45Aijeup6mqEmOWGzYabaVQ.jpg',
      release_date: '2024-04-25',
      title: 'Zak & Wowo: The Legend of Lendarys',
      video: false,
      vote_average: 7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: '/rZmijM6poWf1nNItkZZ8H3gMkX7.jpg',
      genre_ids: [16, 12, 28, 14],
      id: 1147416,
      original_language: 'fr',
      original_title: 'Miraculous World : Londres, la course contre le temps',
      overview:
        "To save the future from a terrible fate, Marinette becomes Chronobug and teams up with Bunnyx to defeat a mysterious opponent who travels through time. Who is this new supervillain, and why are they obsessed with exposing Marinette's secret superhero identity? Marinette's only hope is to defeat her new opponent to prevent the end of Ladybug and time itself!",
      popularity: 469.365,
      poster_path: '/6AtoMpHvs9pxd30KsyK8QmJ9W9M.jpg',
      release_date: '2024-11-14',
      title: 'Miraculous World, London: At the Edge of Time',
      video: false,
      vote_average: 7.851,
      vote_count: 121,
    },
    {
      adult: false,
      backdrop_path: '/gtlPLfpYRdswr4tCeJMxQefCyGo.jpg',
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: 'en',
      original_title: 'Interstellar',
      overview:
        'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
      popularity: 381.192,
      poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      release_date: '2014-11-05',
      title: 'Interstellar',
      video: false,
      vote_average: 8.4,
      vote_count: 36172,
    },
    {
      adult: false,
      backdrop_path: '/sQbFupSWM9wUdPj96NZNUOFSP5.jpg',
      genre_ids: [28, 12, 53],
      id: 1000075,
      original_language: 'fr',
      original_title: "Largo Winch: Le prix de l'argent",
      overview:
        "Largo Winch, devastated by the kidnapping of his son, realizes that if he finds those responsible for his bankruptcy, maybe he'll see his son again.",
      popularity: 423.952,
      poster_path: '/myS41ZUmFvslkT8LeD2irAKxyrf.jpg',
      release_date: '2024-07-31',
      title: 'The Price of Money: A Largo Winch Adventure',
      video: false,
      vote_average: 6.496,
      vote_count: 132,
    },
    {
      adult: false,
      backdrop_path: '/lrP1TQf3stZveNEyviUUcSh8HLA.jpg',
      genre_ids: [28, 12, 10751, 35],
      id: 675353,
      original_language: 'en',
      original_title: 'Sonic the Hedgehog 2',
      overview:
        'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
      popularity: 357.677,
      poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
      release_date: '2022-03-30',
      title: 'Sonic the Hedgehog 2',
      video: false,
      vote_average: 7.485,
      vote_count: 5202,
    },
    {
      adult: false,
      backdrop_path: '/zViRwl3ySscZnbXZJ2Q9wq3SeUG.jpg',
      genre_ids: [16, 878, 12, 10751],
      id: 698687,
      original_language: 'en',
      original_title: 'Transformers One',
      overview:
        'The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.',
      popularity: 369.52,
      poster_path: '/iRCgqpdVE4wyLQvGYU3ZP7pAtUc.jpg',
      release_date: '2024-08-14',
      title: 'Transformers One',
      video: false,
      vote_average: 8.086,
      vote_count: 1021,
    },
    {
      adult: false,
      backdrop_path: '/fyeyxFzZ3qYqDsaMVYF6sq3pp2n.jpg',
      genre_ids: [28, 12, 53],
      id: 1167271,
      original_language: 'en',
      original_title: 'Weekend in Taipei',
      overview:
        'A former DEA agent and a former undercover operative revisit their romance during a fateful weekend in Taipei, unaware of the dangerous consequences of their past.',
      popularity: 356.139,
      poster_path: '/qSc0AUvs8mRy00R9y8QYEHWIAQ9.jpg',
      release_date: '2024-09-19',
      title: 'Weekend in Taipei',
      video: false,
      vote_average: 6.2,
      vote_count: 116,
    },
    {
      adult: false,
      backdrop_path: '/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg',
      genre_ids: [28, 35, 80, 53, 12],
      id: 573435,
      original_language: 'en',
      original_title: 'Bad Boys: Ride or Die',
      overview:
        'After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.',
      popularity: 339.1,
      poster_path: '/oGythE98MYleE6mZlGs5oBGkux1.jpg',
      release_date: '2024-06-05',
      title: 'Bad Boys: Ride or Die',
      video: false,
      vote_average: 7.413,
      vote_count: 2648,
    },
    {
      adult: false,
      backdrop_path: '/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg',
      genre_ids: [28, 12, 53, 80],
      id: 7451,
      original_language: 'en',
      original_title: 'xXx',
      overview:
        'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
      popularity: 313.13,
      poster_path: '/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg',
      release_date: '2002-08-09',
      title: 'xXx',
      video: false,
      vote_average: 5.94,
      vote_count: 4318,
    },
    {
      adult: false,
      backdrop_path: '/llIXQAndg5kB6SWlp6ouUdO7Zxd.jpg',
      genre_ids: [28, 12, 18],
      id: 1084736,
      original_language: 'fr',
      original_title: 'Le Comte de Monte-Cristo',
      overview:
        'Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.',
      popularity: 309.607,
      poster_path: '/sAT1P3FGhtJ68anUyJScnMu8t1l.jpg',
      release_date: '2024-06-28',
      title: 'The Count of Monte Cristo',
      video: false,
      vote_average: 8.1,
      vote_count: 1281,
    },
  ],
  total_pages: 1178,
  total_results: 23550,
};
